# Generated by Django 5.0.2 on 2025-03-28 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_playing', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_room', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='local-songs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('song_position', models.FloatField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='uploadRoom.musicroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='song-covers/')),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='uploadRoom.song')),
            ],
            options={
                'verbose_name': 'Song Information',
                'verbose_name_plural': 'Song Information',
            },
        ),
    ]
