# Generated by Django 5.0.2 on 2025-04-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='cover_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
